version: '3.8'

services:
  hello-app:
    build: .
    container_name: hello-container
    environment:
      replace_world_with_name: ${replace_world_with_name:-world}

    ports:
      - "8000:8000"
